##
## All connections used by Clongus:
##
---
ADGroupMaintenance:
- connection: &HRFiles
    !FileConnection
    name: HR_files
    description: file location for HR files
    path: configs/

- connection: &LDAP_RP
    !LdapConnection
    name: AD_LDAP
    description: Connection to resspotter.home DC
    url: ldaps://192.168.0.3
    cert: xxx
    credential:
      username: CN=sta_ldap,OU=testingStuff,DC=reespotter,DC=home
      password: asdf345SDFg345SD
    baseDN: DC=reespotter,DC=home

- connection: &GoogleWorkspace
    !RestConnection
    name: GoogleWorkspace
    serviceEndpoint: https://admin.googleapis.com/
    authUrl: https://accounts.google.com/o/oauth2/auth
    tokenUrl: https://accounts.google.com/o/oauth2/token
#    scopes:
#    - https://www.googleapis.com/auth/admin.directory.group
#    sendAttributesAs: parameters ## vs path vs content vs headers?      
#   proxy:
#     host: 1.2.3.4
#     port: 3128
    credential:
      !OAuth2
      clientId: 810534103116-hvo5mesopj458s1mjtl9vitkm2t566hd.apps.googleusercontent.com
      secret: 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
      refreshToken: 1//03pxh9IlUZZv2CgYIARAAGAMSNwF-L9Irt6Fhta_I-GqhfT7CG74FQ9l8IZ_-rS1qp7Tsyh0nNs98PiImBjYMEoPn0GmH_pY70g0
    requestParameters:
      domain: sebet.org.uk
#    endpointDetails:
#    - create:
#    - list:
#    - update:
#    - remove:

- connection: &Office365
    !RestConnection
    name: Office365
    serviceEndpoint: https://graph.microsoft.com
#    sendAttributesAs: parameters ## vs path vs content vs headers?      
    credential:
      clientId: 810534103116-hvo5mesopj458s1mjtl9vitkm2t566hd.apps.googleusercontent.com
      secret: see json
#    endpointDetails:
#    - create:
#    - list:
#    - update:
#    - remove:

- connection: &MariaDB
    !SQLConnection
    name: SQL calendar database
    description: Database of calendars, events, subscriptions
    url: jdbc:mariadb://localhost:3306/sta
    credential:
      username: sta
      password: sta
