## Task to create new calendar objects in SQL from AD Department groups.
##
---
SQLCalendar:

- connection: &LDAP_RP
    !LdapConnection
    name: AD_LDAP
    description: Connection to reespotter.home DC

    url: ldaps://192.168.0.3
    cert: xxx
    credential:
      username: CN=sta_ldap,OU=testingStuff,DC=reespotter,DC=home
      password: asdf345SDFg345SD
    baseDN: DC=reespotter,DC=home

- query: &ADDepartments
    ## TO DO: Should be objectQuery?
    !LdapObjectQuery
    name: AD_groups_departments
    description: Read-write access to manage groups in departments OU
    connection: *LDAP_RP
    subOU: OU=groups,OU=testingStuff
    filter: (objectClass=group)
    scope: SUBTREE
#    identifier:
#      attributes:
#      - sAMAccountName

- connection: &MariaDB
    !SQLConnection
    name: SQL calendar database
    description: Database of calendars, events, subscriptions
    url: jdbc:mariadb://localhost:3306/sta
#    driver: mariadb
#    hostname: localhost
#    port: 3306
#    database: sta
    credential:
      username: sta
      password: sta

#queries:
- query: &SQLCalendars
    !SQLQuery
    name: SQL Calendars
    description: table of calendars
    connection: *MariaDB
    table: calendars
    primaryKeyFields:
    - id
#    identifier:
#      attributes:
#      - subject
#tasks:
- task:
    !SimpleTask
    name: Departments_create_HR_AD
    description: Manage AD groups for departments
    source: 
      query: *ADDepartments
    target: 
      query: *SQLCalendars
##  action: CREATE
#    ## series of pattern to try to match things in source with things in target 
    matchers:
    - !RegexMatcher
      name: match_name
#      !regexMatcher
      sourceSignature:
        attributes: 
        - name
      targetSignature:
        attributes: 
        - subject
#      condition: caseInsensitiveExactMatch
   
  ## should state source or target I think (source by default?)... so also targetAttributes
  ## delimiter? default? set alt
 #   filters:
#  #- name: left date hasnt happened yet
#  #  sourceAttributes: endDate
#  #  comparator: lessThan
#  #  value: today
  #  - name: only create and update
   #   actions:
    #  - CREATE
     # - UPDATE
#  
#  ## these are the values for each attribute for the new target thing:
    attributes:
    - !CopyAttribute
      attribute: subject
      source: cn
    - !RegexAttribute
      attribute: ref
      sources:
      - sAMAccountName
      pattern: s/(\w+\s?\w*[^s])$/$1 is on its own/
    - !RegexAttribute
      attribute: ref
      sources:
      - sAMAccountName
      pattern: s/(\w+\s?\w*s)$/$1 are legion/
